
package controller;

import entity.Produto;
import java.util.List;
import javax.swing.JOptionPane;
import service.ProdutoService;

public class NovoProdutoController extends javax.swing.JFrame {
    
     private Produto produto = new Produto();
    int linha = 0;


    /**
     * Creates new form NovoController
     */
     public NovoProdutoController() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public NovoProdutoController(Produto produto, int linha) {
        this.produto = produto;
        this.linha = linha;
        initComponents();
        this.setLocationRelativeTo(null);
        jbSalvar.setText("Editar");
        preencherCampos(produto);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbDescricao = new javax.swing.JLabel();
        jbPreco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbNome = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jtfNomeProduto = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();
        jtfPreco = new javax.swing.JTextField();
        jtfQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("NOVO PRODUTO");

        jbDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbDescricao.setText("Descrição:");

        jbPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbPreco.setText("Preço:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade:");

        jbNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbNome.setText("Nome:");

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbCancelar.setText("Cancelar");

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbNome)
                    .addComponent(jbDescricao)
                    .addComponent(jbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfNomeProduto)
                    .addComponent(jtfDescricao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNome)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDescricao)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPreco)
                    .addComponent(jLabel4)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
         try {
            ProdutoService produtoService = new ProdutoService();
            this.produto = lerValoresDosCampos();
            if (jbSalvar.getText().equals("Salvar")) {
                produtoService.salvarProduto(this.produto);
                this.dispose();
            } else {
                produtoService.editarProduto(this.produto);
                this.dispose();
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Você informou algum valor inválido");
        }    
    }//GEN-LAST:event_jbSalvarActionPerformed

      private Produto lerValoresDosCampos() {
        this.produto.setNome(jtfNomeProduto.getText());
        this.produto.setDescricao(jtfDescricao.getText());
        this.produto.setPreco(Double.parseDouble(jtfPreco.getText()));
        this.produto.setEstoque(Integer.parseInt(jtfQuantidade.getText()));
        return this.produto;
    }

    private void preencherCampos(Produto produto) {
        jtfNomeProduto.setText(produto.getNome());
        jtfDescricao.setText(produto.getDescricao());
        jtfPreco.setText(produto.getPreco() + "");
        jtfQuantidade.setText(produto.getEstoque() + "");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoProdutoController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoProdutoController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoProdutoController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoProdutoController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoProdutoController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jbDescricao;
    private javax.swing.JLabel jbNome;
    private javax.swing.JLabel jbPreco;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfNomeProduto;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfQuantidade;
    // End of variables declaration//GEN-END:variables
}
